version: "3.5"
services:
  courseplatform-redis:
    image: redis:alpine
    container_name: courseplatform-redis
    volumes:
      - courseplatform-redis:/data
    ports:
      - "16377:6379"
    networks:
      - courseplatform

  courseplatform-mysql:
    image: mysql:5.7.22
    container_name: courseplatform-mysql
    working_dir: /application
    volumes:
      - courseplatform-mysql-data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: KBHJ8765ljk767kh
      MYSQL_DATABASE: app
    ports:
      - "2324:3306"
    networks:
      - courseplatform

  courseplatform-webserver:
    image: nginx:alpine
    container_name: courseplatform-webserver
    working_dir: /application
    volumes:
      - ../:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - courseplatform

  courseplatform-php-fpm:
    build: phpdocker/php-fpm
    container_name: courseplatform-php-fpm
    working_dir: /application
    volumes:
      - ../:/application
    ports:
      - "9000"
    networks:
      - courseplatform
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      PHP_IDE_CONFIG: 'serverName=my application'

  courseplatform-scheduler:
    build: phpdocker/php-fpm
    container_name: courseplatform-scheduler
    volumes:
      - ../:/application
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
    networks:
      - courseplatform

  courseplatform-queue:
    build: phpdocker/php-fpm
    container_name: courseplatform-queue
    volumes:
      - ../:/application
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
    networks:
      - courseplatform
  courseplatform-websocket:
    build: phpdocker/php-fpm
    container_name: courseplatform-websocket
    volumes:
      - ../:/application
    ports:
      - "6001:6001"
    environment:
      APP_ENV: local
      CONTAINER_ROLE: websocket
    networks:
      - courseplatform

networks:
  courseplatform:
    driver: bridge

volumes:
  courseplatform-mysql-data:
    driver: "local"
  courseplatform-redis:
    driver: "local"

